require('./app.js');
require('./view1/view1.js');
require('./view2/view2.js');
window.angular = require('./static/js/angular-1.5.8.js');
require('./static/js/angular-route.js');
window.jquery = require('./static/js/jquery.min.js');
//var layer_ = require('./static/js/layer/layer.js');
require('./components/version/version.js');
require('./components/version/version-directive.js');
require('./components/version/interpolate-filter.js');
